In [73]:
import pandas as pd
df = pd.read_csv("spambase.data",header=None)

Read input and shuffle randomly
---

In [74]:
from sklearn.utils import shuffle
df = pd.DataFrame(shuffle(df))
df

0     1     2     3     4     5     6     7     8     9   ...      48  \
1689  0.00  0.00  0.00  0.00  1.04  1.04  0.00  0.00  0.00  0.00  ...   0.000   
2639  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
1805  0.00  0.00  0.68  0.00  0.00  0.00  0.00  1.36  0.00  0.00  ...   0.000   
2010  0.39  0.39  0.00  0.00  0.39  0.00  0.00  0.00  0.00  0.39  ...   0.125   
856   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
2665  0.00  0.00  0.43  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.318   
4524  0.00  0.00  0.00  0.00  0.00  0.37  0.00  0.00  0.00  0.00  ...   0.000   
180   0.34  0.25  0.25  0.00  0.08  0.43  0.08  0.25  0.08  1.46  ...   0.000   
2701  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
1431  0.00  0.00  0.93  0.00  0.00  0.00  0.00  0.00  0.00  2.80  ...   0.000   
154   0.00  0.00  1.68  0.00  0.33  0.00  0.00  0.00  0.00  0.33  ...   0.000   
1894  0.11  0.05  0.22  0.00  0.22  0.05  0.00  0.00  0.05  0.11  ...   0.025   
393   0.60  0.00  0.00  0.00  1.21  0.00  0.60  0.00  0.00  0.00  ...   0.000   
4061  0.00  0.00  0.00  0.00  0.96  0.48  0.00  0.00  0.48  0.00  ...   0.000   
2151  0.00  0.00  0.00  0.00  4.76  0.00  0.00  0.00  0.00  0.00  ...   0.000   
488   0.08  0.08  0.76  0.00  0.85  1.02  0.25  0.17  0.59  0.08  ...   0.000   
1456  0.00  0.51  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.51  ...   0.000   
2253  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
46    0.18  0.00  0.18  0.00  1.57  0.36  0.06  0.06  0.06  0.12  ...   0.010   
1629  0.40  0.00  0.00  0.00  0.80  0.00  0.40  2.80  0.00  1.20  ...   0.052   
2462  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
3411  0.00  0.00  0.00  0.00  1.05  0.00  0.00  0.00  0.00  0.00  ...   0.000   
3829  0.00  0.00  0.28  0.00  0.84  0.00  0.00  0.00  0.00  0.00  ...   0.000   
870   0.00  0.00  0.00  0.00  1.46  0.00  0.83  0.00  0.20  1.04  ...   0.182   
2439  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
2116  0.00  0.00  0.09  0.00  0.09  0.00  0.00  0.55  0.00  0.09  ...   0.012   
3118  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
27    0.00  0.00  0.00  0.00  0.00  0.00  1.66  0.00  0.00  0.00  ...   0.000   
2076  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
3224  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
1526  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
2667  0.07  0.00  0.14  0.00  0.07  0.00  0.00  0.00  0.74  0.00  ...   0.116   
4309  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   3.885   
2363  0.00  0.18  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
834   0.00  0.00  0.51  0.00  0.51  0.00  0.00  0.51  0.00  0.00  ...   0.000   
2520  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
329   0.00  0.00  0.16  0.16  0.32  0.00  0.16  0.00  0.65  0.16  ...   0.000   
1459  0.70  0.00  1.05  0.00  0.00  0.00  0.00  1.40  0.35  0.35  ...   0.000   
3606  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
4375  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
1313  0.54  0.13  0.38  0.00  0.05  0.16  0.00  0.05  0.35  0.16  ...   0.000   
3162  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
1400  0.00  0.00  1.63  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
389   0.08  0.00  0.93  0.00  1.52  0.33  0.00  0.08  0.67  0.00  ...   0.012   
2587  0.00  0.61  0.00  0.00  1.22  0.00  0.00  0.00  0.00  3.68  ...   0.000   
2263  0.00  0.00  0.00  0.00  0.93  0.00  0.00  0.00  0.00  0.00  ...   0.000   
3060  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...   0.000   
2386  0.00  0.00  0.00  0.00  0.00  0.0

Setting up number of training and test data
---

In [75]:
num_rows = len(df.index)
num_train = (int) (num_rows * 0.75)
num_test = num_rows - num_train


In [76]:
x_train = df[0:num_train][df.columns[0:57]]
y_train = df[0:num_train][df.columns[-1:]]

In [77]:
x_test = df[num_train:num_rows][df.columns[0:57]]
y_test = df[num_train:num_rows][df.columns[-1:]]
y_test

57
359    1
337    1
2692   0
3993   0
2482   0
2852   0
568    1
1189   1
1797   1
2606   0
3361   0
3570   0
409    1
2634   0
4254   0
2635   0
1953   0
3688   0
3683   0
4082   0
3843   0
4184   0
1670   1
4033   0
2491   0
2261   0
2472   0
3738   0
979    1
2708   0
...   ..
1526   1
2667   0
4309   0
2363   0
834    1
2520   0
329    1
1459   1
3606   0
4375   0
1313   1
3162   0
1400   1
389    1
2587   0
2263   0
3060   0
2386   0
2481   0
2511   0
1871   0
3734   0
1300   1
189    1
2593   0
1568   1
1146   1
3413   0
2262   0
2072   0

[1151 rows x 1 columns]

In [81]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(x_train.values, y_train.values.transpose()[0])

predicted_test_labels = y_pred.predict(x_test.values)
actual_test_labels = y_test.values.transpose()[0]

#y_pred.decision_function(x_test)

GaussianNB(priors=None)

Computing Accuracy
---

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(predicted_test_labels, actual_test_labels)

0.82971329278887929

In [48]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)
y_pred = mnb.fit(x_train.values, y_train.values.transpose()[0])

predicted_test_labels = y_pred.predict(x_test.values)
actual_test_labels = y_test.values.transpose()[0]

In [49]:
accuracy_score(predicted_test_labels, actual_test_labels)

0.77845351867940926

In [50]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)
y_pred = bnb.fit(x_train.values, y_train.values.transpose()[0])

predicted_test_labels = y_pred.predict(x_test.values)
actual_test_labels = y_test.values.transpose()[0]

In [51]:
accuracy_score(predicted_test_labels, actual_test_labels)

0.90703735881841874

In [52]:
from sklearn.svm import SVC
svm = SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    degree=3, gamma='auto', kernel='rbf',
    max_iter=-1.0, probability=False, shrinking=True,
    tol=0.001, verbose=False)

y_pred = svm.fit(x_train.values, y_train.values.transpose()[0])
predicted_test_labels = y_pred.predict(x_test.values)
actual_test_labels = y_test.values.transpose()[0]

In [53]:
accuracy_score(predicted_test_labels, actual_test_labels)

0.8262380538662033

In [54]:
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression()
lgr.fit(x_train.values, y_train.values.transpose()[0])
y_pred = lgr.predict(x_test.values)
print(classification_report(y_test.values, y_pred))

             precision    recall  f1-score   support

          0       0.93      0.96      0.95       688
          1       0.94      0.90      0.92       463

avg / total       0.94      0.94      0.94      1151



In [55]:
from sklearn.metrics import classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)
lda.fit(x_train.values, y_train.values.transpose()[0])
y_pred =lda.predict(x_test.values)
print(classification_report(y_test.values, y_pred))

             precision    recall  f1-score   support

          0       0.88      0.96      0.92       688
          1       0.93      0.80      0.86       463

avg / total       0.90      0.89      0.89      1151



In [14]:
from sklearn import preprocessing
import numpy as np
def derivative(x):
    return x * (1.0 - x)
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))
X = []
Y = []
# read the training data
with open(‘Train.csv’) as f:
    for line in f:
        curr = line.split(‘,’)
        new_curr = [1]
        for item in curr[:len(curr) — 1]:
            new_curr.append(float(item))
        X.append(new_curr)
        Y.append([float(curr[-1])])
X = np.array(X)
X = preprocessing.scale(X) # feature scaling
Y = np.array(Y)
# the first 2500 out of 3000 emails will serve as training data
X_train = X[0:2500]
Y_train = Y[0:2500]
# the rest 500 emails will serve as testing data
X_test = X[2500:]
y_test = Y[2500:]
X = X_train
y = Y_train
# we have 3 layers: input layer, hidden layer and output layer
# input layer has 57 nodes (1 for each feature)
# hidden layer has 4 nodes
# output layer has 1 node
dim1 = len(X_train[0])
dim2 = 4
# randomly initialize the weight vectors
np.random.seed(1)
weight0 = 2 * np.random.random((dim1, dim2)) — 1
weight1 = 2 * np.random.random((dim2, 1)) — 1
# you can change the number of iterations
for j in xrange(25000):
    # first evaluate the output for each training email
    layer_0 = X_train
    layer_1 = sigmoid(np.dot(layer_0,weight0))
    layer_2 = sigmoid(np.dot(layer_1,weight1))
    # calculate the error
    layer_2_error = Y_train — layer_2
    # perform back propagation
    layer_2_delta = layer_2_error * derivative(layer_2)
    layer_1_error = layer_2_delta.dot(weight1.T)
    layer_1_delta = layer_1_error * derivative(layer_1)
    # update the weight vectors
    weight1 += layer_1.T.dot(layer_2_delta)
    weight0 += layer_0.T.dot(layer_1_delta)
# evaluation on the testing data
layer_0 = X_test
layer_1 = sigmoid(np.dot(layer_0,weight0))
layer_2 = sigmoid(np.dot(layer_1,weight1))
correct = 0
# if the output is > 0.5, then label as spam else no spam
for i in xrange(len(layer_2)):
    if(layer_2[i][0] > 0.5):
        layer_2[i][0] = 1
    else:
        layer_2[i][0] = 0
    if(layer_2[i][0] == y_test[i][0]):
        correct += 1
# printing the output
print “total = “, len(layer_2)
print “correct = “, correct
print “accuracy = “, correct * 100.0 / len(layer_2)

SyntaxError: invalid syntax (<ipython-input-14-4d8968da7b17>, line 4)

In [59]:
from sklearn.metrics import roc_curve, auc
n_classes = 2
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = roc_curve(y_test.ravel(), y_pred.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

TypeError: unhashable type

In [67]:


import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp

# Import some data to play with
iris = datasets.load_iris()
X = iris.data
y = iris.target


# Binarize the output
y = label_binarize(y, classes=[0, 1, 2])
n_classes = y.shape[1]

# Add noisy features to make the problem harder
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape
print n_classes
X = np.c_[X, random_state.randn(n_samples, 200 * n_features)]

# shuffle and split training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5,
                                                    random_state=0)

# Learn to predict each class against the other
classifier = OneVsRestClassifier(svm.SVC(kernel='linear', probability=True,
                                 random_state=random_state))
y_score = classifier.fit(X_train, y_train).decision_function(X_test)

print y_score

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = roc_curve(y_test.ravel(), y_score.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

plt.figure()
lw = 2
plt.plot(fpr[2], tpr[2], color='darkorange',
         lw=lw, label='ROC curve (area = %0.2f)' % roc_auc[2])
plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")
#plt.show()

3
[[-0.76305896 -0.36472635  0.1239796 ]
 [-0.20238399 -0.63148982 -0.16616656]
 [ 0.11808492 -0.80262259 -0.32062486]
 [-0.90750303 -0.1239792   0.02184016]
 [-0.01108555 -0.27918155 -0.71882525]
 [-0.60521037 -0.34728075 -0.05851787]
 [ 0.02264569 -0.24507866 -0.79094201]
 [-0.61115098  0.1827259  -0.57154703]
 [-0.37590649 -0.24062697 -0.38892819]
 [-0.47019698 -0.25733679 -0.27501927]
 [-0.42194767 -0.30275351 -0.28027547]
 [-0.33545871 -0.70306393  0.02538619]
 [-0.22711497 -0.64064389 -0.13452752]
 [-0.07836815 -0.46342889 -0.45930643]
 [-0.533757   -0.26521263 -0.20026826]
 [ 0.09973063 -0.55326984 -0.56156984]
 [-0.71354879 -0.04231832 -0.24317009]
 [-0.55067912 -0.13785396 -0.31413579]
 [ 0.37989555 -0.99673681 -0.3909524 ]
 [-0.11088917 -0.91357544  0.03129667]
 [-0.70721114 -0.06430956 -0.21412904]
 [-0.02407429 -0.45895598 -0.51928682]
 [-0.25004251 -0.80100991  0.04076059]
 [ 0.12688003 -0.70987418 -0.41083444]
 [-0.68224184 -0.20724969 -0.1202643 ]
 [-0.0800568  -0.366955